def papagaio(voltagem, estado='é um cadáver', ação='voar', tipo='Azul Norueguês'):
    print("-- Este papagaio não conseguiria", ação, end=' ')
    print("nem se você desse um choque de", voltagem, "volts!")
    print("-- Plumagem formosa, o", tipo)
    print("-- Ele", estado, "!")

print("$==============================================$")
papagaio(1000)
print("$==============================================$")
papagaio(voltagem=1000)
print("$==============================================$")
papagaio(voltagem=1000000, ação='fazer VOOOOOM')
print("$==============================================$")
papagaio(ação='fazer VOOOOOM', voltagem=1000000)
print("$==============================================$")
papagaio('um milhão', 'sem vida', 'pular')
print("$==============================================$")
papagaio('mil', estado='estaria no céu')
print("$==============================================$")
